/**
 * Constantes para tipos de eventos de logging
 * Usar estas constantes en lugar de strings literales
 */
export const LOG_EVENTS = {
  // Eventos de actualización de proyección
  ON_PROJECTION_UPDATE: 'ON_PROJECTION_UPDATE',
  ON_PROJECTION_UPDATE_STARTED: 'ON_PROJECTION_UPDATE_STARTED',
  ON_PROJECTION_UPDATE_COMPLETED: 'ON_PROJECTION_UPDATE_COMPLETED',
  ON_PROJECTION_UPDATE_FAILED: 'ON_PROJECTION_UPDATE_FAILED',

  // Eventos de ejecución de métricas
  ON_RUN_STARTED: 'ON_RUN_STARTED',
  ON_RUN_HEARTBEAT: 'ON_RUN_HEARTBEAT',
  ON_RUN_COMPLETED: 'ON_RUN_COMPLETED',
  ON_RUN_FAILED: 'ON_RUN_FAILED',
  ON_RUN_QUEUED: 'ON_RUN_QUEUED',
  ON_RUN_DISPATCHED: 'ON_RUN_DISPATCHED',

  // Eventos de dependencias
  ON_DEPENDENCY_RESOLVED: 'ON_DEPENDENCY_RESOLVED',
  ON_DEPENDENCY_PENDING: 'ON_DEPENDENCY_PENDING',
  ON_ALL_DEPENDENCIES_READY: 'ON_ALL_DEPENDENCIES_READY',

  // Eventos de base de datos
  DB_CONNECTION_ESTABLISHED: 'DB_CONNECTION_ESTABLISHED',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_TRANSACTION_STARTED: 'DB_TRANSACTION_STARTED',
  DB_TRANSACTION_COMMITTED: 'DB_TRANSACTION_COMMITTED',
  DB_TRANSACTION_ROLLED_BACK: 'DB_TRANSACTION_ROLLED_BACK',

  // Eventos de AWS
  SNS_EVENT_PUBLISHED: 'SNS_EVENT_PUBLISHED',
  SNS_EVENT_PUBLISH_FAILED: 'SNS_EVENT_PUBLISH_FAILED',
  SQS_MESSAGE_RECEIVED: 'SQS_MESSAGE_RECEIVED',
  SQS_MESSAGE_PROCESSED: 'SQS_MESSAGE_PROCESSED',
  SQS_MESSAGE_ERROR: 'SQS_MESSAGE_ERROR',
} as const;

export type LogEvent = (typeof LOG_EVENTS)[keyof typeof LOG_EVENTS];

